server:
  port: 8080

spring:
  application:
    name: EduCoon

  # 기본적으로 'local' 프로필을 실행 (내 컴퓨터용)
  profiles:
    active: local

  # 파일 업로드 용량 설정 (공통)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # JPA 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  ai:
    google:
      gemini:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-1.5-flash

jwt:
  secret:
    key: ${JWT_SECRET_KEY:vmdalstkdqkdbalroqkfwkdbalroqkfwkdbalroqkfwkdbalroqkfwkdbalroqkfwkdbalroqkfwkdbalroqkfwkdbalroqkfwkd}
  access-token-expiration: 3600000 # 1시간
  refresh-token-expiration: 1209600000 # 14일

